"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ClipboardPlus } from "lucide-react";
import { submitLeaveRequestAction } from "@/lib/actions-operations";

type Request = { id: string; leave_type: string; starts_at: string; ends_at: string; reason: string; status: string };
const labels: Record<string, string> = { leave: "Cuti", sick: "Sakit", permission: "Izin", overtime: "Lembur" };
export default function LeaveClient({ staffName, requests }: { staffName: string; requests: Request[] }) {
  const [data, setData] = useState({ leaveType: "leave" as "leave" | "sick" | "permission" | "overtime", startsAt: "", endsAt: "", reason: "" }); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async () => { setSaving(true); const result = await submitLeaveRequestAction(data); setSaving(false); setNotice(result.ok ? "Pengajuan terkirim ke owner untuk diperiksa." : result.error || "Pengajuan belum terkirim."); if (result.ok) window.location.reload(); };
  return <main className="kael-hr min-h-screen bg-[#f7f6fc] p-4 pb-20 text-[#232331] sm:p-8"><div className="mx-auto max-w-lg space-y-4"><Link href="/app/staff" className="inline-flex min-h-10 items-center gap-2 text-sm font-bold"><ArrowLeft size={16}/>Kembali</Link><header><p className="font-mono text-[11px] font-bold text-[#7958d8]">KAEL HR</p><h1 className="text-2xl font-black">Izin dan lembur {staffName}</h1><p className="mt-1 text-sm text-[#66667a]">Kirim pengajuan agar owner bisa menyetujui dan menghitungnya dengan jelas.</p></header>{notice&&<div role="status" className="rounded-xl border border-[#15803d] bg-[#dcfce7] p-3 text-sm font-bold text-[#166534]">{notice}</div>}<section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="flex items-center gap-2"><ClipboardPlus size={18}/><h2 className="font-black">Buat pengajuan</h2></div><label className="mt-3 block text-xs font-bold">Jenis<select value={data.leaveType} onChange={e=>setData({...data,leaveType:e.target.value as typeof data.leaveType})} className="field"><option value="leave">Cuti</option><option value="sick">Sakit</option><option value="permission">Izin</option><option value="overtime">Lembur</option></select></label><div className="grid grid-cols-2 gap-2"><label className="mt-3 block text-xs font-bold">Mulai<input type="datetime-local" value={data.startsAt} onChange={e=>setData({...data,startsAt:e.target.value})} className="field"/></label><label className="mt-3 block text-xs font-bold">Selesai<input type="datetime-local" value={data.endsAt} onChange={e=>setData({...data,endsAt:e.target.value})} className="field"/></label></div><label className="mt-3 block text-xs font-bold">Alasan<textarea minLength={5} value={data.reason} onChange={e=>setData({...data,reason:e.target.value})} className="field min-h-24" placeholder="Tulis alasan singkat dan jelas"/></label><button onClick={submit} disabled={saving||!data.startsAt||!data.endsAt||data.reason.length<5} className="primary w-full">Kirim pengajuan</button></section><section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><h2 className="font-black">Riwayat saya</h2><div className="mt-3 space-y-2">{requests.map(x=><div className="rounded-xl border border-[#dedee8] p-3 text-sm" key={x.id}><div className="flex justify-between gap-2"><b>{labels[x.leave_type]||x.leave_type}</b><span className="font-mono text-xs">{x.status}</span></div><p className="mt-1 text-xs text-[#66667a]">{new Date(x.starts_at).toLocaleString("id-ID")} sampai {new Date(x.ends_at).toLocaleString("id-ID")}</p><p className="mt-2">{x.reason}</p></div>)}{!requests.length&&<p className="rounded-xl bg-[#f7f6fc] p-4 text-sm text-[#66667a]">Belum ada pengajuan.</p>}</div></section></div></main>;
}
