"use client";

import { useRef, useState } from "react";
import { Camera, LogIn, LogOut, MapPin } from "lucide-react";
import { recordAttendanceAction } from "@/lib/actions-operations";

export default function AttendanceClient({ staffName, cardCode }: { staffName: string; cardCode: string | null }) {
  const video = useRef<HTMLVideoElement>(null); const canvas = useRef<HTMLCanvasElement>(null); const [selfie,setSelfie]=useState<string | null>(null); const [position,setPosition]=useState<{latitude:number;longitude:number}|null>(null); const [busy,setBusy]=useState(false);
  const camera=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:480},height:{ideal:480}},audio:false});if(video.current){video.current.srcObject=stream;await video.current.play();}}catch{alert("Kamera tidak tersedia. Izinkan akses kamera untuk selfie absensi.");}};
  const capture=()=>{if(!video.current||!canvas.current)return;const c=canvas.current;c.width=360;c.height=360;const ctx=c.getContext("2d");if(!ctx)return;ctx.drawImage(video.current,0,0,360,360);setSelfie(c.toDataURL("image/jpeg",.65));const stream=video.current.srcObject as MediaStream|null;stream?.getTracks().forEach(t=>t.stop());video.current.srcObject=null;};
  const locate=()=>navigator.geolocation.getCurrentPosition(p=>setPosition({latitude:p.coords.latitude,longitude:p.coords.longitude}),()=>alert("Lokasi tidak terbaca. Izinkan akses lokasi."),{enableHighAccuracy:true,timeout:10000});
  const submit=async(direction:"in"|"out")=>{setBusy(true);const result=await recordAttendanceAction({direction,latitude:position?.latitude,longitude:position?.longitude,selfieUrl:selfie??undefined,method:cardCode?"nfc":position?"location":"self"});setBusy(false);if(!result.ok)alert(result.error);else alert(direction==="in"?"Absensi masuk tercatat.":"Absensi pulang tercatat.");};
  return <main className="min-h-screen bg-[#f7f6fc] p-4 text-[#232331] sm:p-8"><div className="mx-auto max-w-md space-y-5"><header><p className="font-mono text-[11px] font-bold text-[#7958d8]">KAEL HR</p><h1 className="text-2xl font-black">Absensi {staffName}</h1><p className="mt-1 text-sm text-[#66667a]">Ambil selfie dan lokasi sebelum mencatat kehadiran.</p></header><section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="aspect-square overflow-hidden rounded-lg bg-[#232331]"><video ref={video} muted playsInline className="h-full w-full object-cover"/>{selfie&&<img src={selfie} alt="Selfie absensi" className="h-full w-full object-cover"/>}</div><canvas ref={canvas} className="hidden"/><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={camera} className="inline-flex items-center justify-center gap-2 rounded-lg border-2 border-[#232331] bg-white p-2 text-sm font-bold"><Camera size={16}/>Buka kamera</button><button onClick={capture} className="rounded-lg border-2 border-[#232331] bg-[#d9ff57] p-2 text-sm font-bold">Ambil selfie</button><button onClick={locate} className="col-span-2 inline-flex items-center justify-center gap-2 rounded-lg border-2 border-[#232331] bg-white p-2 text-sm font-bold"><MapPin size={16}/>{position?"Lokasi terbaca":"Ambil lokasi"}</button></div></section><div className="grid grid-cols-2 gap-3"><button disabled={busy} onClick={()=>submit("in")} className="inline-flex items-center justify-center gap-2 rounded-lg border-2 border-[#232331] bg-[#7958d8] p-3 font-bold text-white disabled:opacity-50"><LogIn size={17}/>Masuk</button><button disabled={busy} onClick={()=>submit("out")} className="inline-flex items-center justify-center gap-2 rounded-lg border-2 border-[#232331] bg-white p-3 font-bold disabled:opacity-50"><LogOut size={17}/>Pulang</button></div></div></main>;
}
