"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Activity, ArrowLeft, CalendarClock, KeyRound, Search, ShieldCheck, Store } from "lucide-react";
import { adminResetOwnerPasswordAction, adminSetDemoExpiryAction } from "@/lib/actions";

type Tenant = { id: string; name: string; business_type: string; is_demo: boolean; demo_expires_at: string | null; custom_domain: string | null; staff_count: number; active_modules: number; low_stock: number; pending_deposits: number; pending_orders: number; last_review_sync: string | null; messaging_provider: string | null; messaging_enabled: boolean | null };
type Audit = { id: string; action: string; entity_type: string; created_at: string; business_name: string | null; actor_name: string | null };

export default function ControlClient({ data }: { data: { tenants: Tenant[]; recentAudit: Audit[] } }) {
  const [query,setQuery]=useState(""); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState<string|null>(null); const [passwordFor,setPasswordFor]=useState<string|null>(null); const [password,setPassword]=useState("");
  const tenants=useMemo(()=>data.tenants.filter(t=>t.name.toLowerCase().includes(query.toLowerCase())),[data.tenants,query]);
  const reset=async(id:string)=>{setBusy(true);const r=await adminResetOwnerPasswordAction(id,password);setBusy(false);if(!r.ok)return setNotice(r.error);setNotice(`Password sementara owner ${r.data.email} sudah diubah.`);setPasswordFor(null);setPassword("");location.reload();};
  const demo=async(id:string,isDemo:boolean)=>{const expires=isDemo?null:new Date(Date.now()+30*86400000).toISOString().slice(0,10);setBusy(true);const r=await adminSetDemoExpiryAction(id,expires);setBusy(false);setNotice(r.ok?(expires?"Tenant ditandai demo 30 hari.":"Tenant dipromosikan menjadi pelanggan."):r.error);if(r.ok)location.reload();};
  const issue=(t:Tenant)=>t.low_stock+t.pending_deposits+t.pending_orders;
  return <main className="min-h-screen bg-[#f7f6fc] p-4 text-[#232331] sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap items-end justify-between gap-3"><div className="flex items-center gap-3"><Link href="/admin/businesses" className="flex h-10 w-10 items-center justify-center rounded-lg border-2 border-[#232331] bg-white"><ArrowLeft size={17}/></Link><div><p className="font-mono text-[11px] font-bold text-[#7958d8]">KAEL CONTROL CENTER</p><h1 className="text-2xl font-black">Operasi semua tenant</h1></div></div><Link href="/admin/cards" className="rounded-lg border-2 border-[#232331] bg-white px-3 py-2 text-sm font-bold">Kartu</Link></header>
  {notice&&<div className="rounded-lg border-2 border-[#232331] bg-[#d9ff57] p-3 text-sm font-bold">{notice}</div>}
  <section className="grid gap-3 sm:grid-cols-4"><Metric icon={<Store size={16}/>} label="Tenant" value={data.tenants.length}/><Metric icon={<Activity size={16}/>} label="Perlu perhatian" value={data.tenants.filter(t=>issue(t)>0).length}/><Metric icon={<CalendarClock size={16}/>} label="Demo aktif" value={data.tenants.filter(t=>t.is_demo).length}/><Metric icon={<ShieldCheck size={16}/>} label="WA aktif" value={data.tenants.filter(t=>t.messaging_enabled).length}/></section>
  <section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Kesehatan tenant</h2><p className="text-xs text-[#66667a]">Stok minimum, pembayaran tertunda, DP, Google sync, dan channel WhatsApp.</p></div><label className="relative"><Search size={15} className="absolute left-3 top-2.5 text-[#66667a]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari tenant" className="rounded-lg border border-[#232331] py-2 pl-9 pr-3 text-sm"/></label></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-[#dedee8] font-mono text-[10px] text-[#66667a]"><tr><th className="p-2">TENANT</th><th className="p-2">MODUL/STAF</th><th className="p-2">HEALTH</th><th className="p-2">INTEGRASI</th><th className="p-2">DEMO</th><th className="p-2 text-right">AKSI</th></tr></thead><tbody>{tenants.map(t=><tr key={t.id} className="border-b border-[#eee] align-top"><td className="p-2"><b>{t.name}</b><p className="mt-1 text-xs text-[#66667a]">{t.business_type} {t.custom_domain?`· ${t.custom_domain}`:""}</p></td><td className="p-2">{t.active_modules} modul<br/><span className="text-xs text-[#66667a]">{t.staff_count} staf</span></td><td className="p-2"><span className={issue(t)?"font-bold text-[#c2410c]":"text-[#15803d]"}>{issue(t)?`${issue(t)} item perlu cek`:"Sehat"}</span><p className="mt-1 text-xs text-[#66667a]">Stok {t.low_stock} · order {t.pending_orders} · DP {t.pending_deposits}</p></td><td className="p-2 text-xs">WA: {t.messaging_enabled?"aktif":"belum"}<br/>Google: {t.last_review_sync?new Date(t.last_review_sync).toLocaleDateString("id-ID"):"belum sync"}</td><td className="p-2 text-xs">{t.is_demo?`Sampai ${t.demo_expires_at}`:"Pelanggan"}</td><td className="p-2 text-right"><div className="flex justify-end gap-2"><button disabled={busy} onClick={()=>demo(t.id,t.is_demo)} className="rounded-md border border-[#232331] bg-white px-2 py-1 text-xs font-bold">{t.is_demo?"Promosi":"Jadi demo"}</button><button disabled={busy} onClick={()=>setPasswordFor(t.id)} className="rounded-md border border-[#232331] bg-[#f0edff] p-1.5" title="Reset password owner"><KeyRound size={14}/></button></div>{passwordFor===t.id&&<div className="mt-2 flex justify-end gap-1"><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password sementara" className="w-40 rounded border border-[#232331] p-1 text-xs"/><button onClick={()=>reset(t.id)} disabled={busy||password.length<10} className="rounded bg-[#232331] px-2 text-xs font-bold text-white">Simpan</button></div>}</td></tr>)}</tbody></table></div></section>
  <section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><h2 className="font-bold">Audit terbaru</h2><div className="mt-3 space-y-2">{data.recentAudit.map(a=><div className="flex flex-wrap justify-between gap-2 border-b border-[#eee] pb-2 text-xs" key={a.id}><span><b>{a.business_name||"Platform"}</b> · {a.action}</span><span className="text-[#66667a]">{a.actor_name||"sistem"} · {new Date(a.created_at).toLocaleString("id-ID")}</span></div>)}</div></section></div></main>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="rounded-xl border-2 border-[#232331] bg-white p-4 shadow-ink-md"><div className="flex items-center gap-2 text-[#7958d8]">{icon}<span className="font-mono text-[10px] font-bold">{label}</span></div><p className="mt-2 text-2xl font-black">{value}</p></div>}
