"use client";

import { useState } from "react";
import { CalendarClock, CheckCircle2, XCircle } from "lucide-react";
import { updatePublicBookingAction } from "@/lib/actions-operations";

type Appointment = { public_token: string; business_name: string; service_name: string; starts_at: string; status: string; deposit_amount: number; deposit_status: string };

export default function PublicBookingManageClient({ appointment }: { appointment: Appointment }) {
  const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [reschedule, setReschedule] = useState("");
  const update = async (cancel: boolean) => { setBusy(true); const result = await updatePublicBookingAction(appointment.public_token, cancel ? { cancel: true } : { startsAt: new Date(reschedule).toISOString() }); setBusy(false); if (!result.ok) return setNotice(result.error); if (result.data.publicToken) window.location.href = `${window.location.pathname.replace(appointment.public_token, result.data.publicToken)}`; else setNotice(cancel ? "Booking berhasil dibatalkan." : "Booking berhasil dijadwalkan ulang."); };
  const canEdit = ["pending_deposit", "confirmed"].includes(appointment.status);
  return <main className="min-h-screen bg-[#f7f6fc] p-4 text-[#232331] sm:p-8"><div className="mx-auto max-w-md space-y-4"><section className="rounded-2xl border-2 border-[#232331] bg-white p-5 text-center shadow-ink-md"><CheckCircle2 className="mx-auto text-[#15803d]" size={28} /><p className="mt-3 font-mono text-[11px] font-bold text-[#7958d8]">BOOKING KAMU</p><h1 className="mt-1 text-xl font-black">{appointment.business_name}</h1><p className="mt-4 font-bold">{appointment.service_name}</p><p className="mt-1 text-sm text-[#66667a]">{new Date(appointment.starts_at).toLocaleString("id-ID")}</p><p className="mt-3 rounded-lg bg-[#f0edff] p-3 text-sm">Status: <b>{appointment.status === "pending_deposit" ? "Menunggu DP" : appointment.status}</b>{appointment.deposit_amount ? <><br />DP: Rp {Number(appointment.deposit_amount).toLocaleString("id-ID")} ({appointment.deposit_status})</> : null}</p></section>{notice && <p role="status" className="rounded-xl border border-[#b45309] bg-[#fff7ed] p-3 text-sm font-bold text-[#9a3412]">{notice}</p>}{canEdit && <section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><h2 className="font-black">Ubah jadwal atau batalkan</h2><p className="mt-1 text-sm text-[#66667a]">Pilih waktu baru. Sistem akan memeriksa slot sebelum perubahan dibuat.</p><label className="mt-3 block text-xs font-bold">Waktu baru<input type="datetime-local" value={reschedule} onChange={(event) => setReschedule(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-[#232331] p-2" /></label><button disabled={busy || !reschedule} type="button" onClick={() => update(false)} className="mt-3 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border-2 border-[#232331] bg-[#d9ff57] text-sm font-black disabled:opacity-50"><CalendarClock size={16} />Jadwalkan ulang</button><button disabled={busy} type="button" onClick={() => update(true)} className="mt-2 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-[#b91c1c] bg-white text-sm font-bold text-[#b91c1c]"><XCircle size={16} />Batalkan booking</button></section>}</div></main>;
}
