"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BriefcaseBusiness, Calculator, Landmark, Package, Plus, ReceiptText, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import type { Business, FinanceAsset, FinancePocket, FinanceSummary, FinanceTransaction, InventoryItem } from "@/lib/types";
import { adjustInventoryStockAction, createFinanceTransactionAction, recordInventoryPurchaseAction, saveFinanceAssetAction, saveFinancePocketAction, saveInventoryItemAction } from "@/lib/actions";
import { formatBusinessDate, formatRupiah } from "@/lib/formatters";

const today = () => new Date().toISOString().slice(0, 10);

export default function FinanceOperationsClient({ business, pockets, transactions, assets, inventory, summary }: { business: Business | null; pockets: FinancePocket[]; transactions: FinanceTransaction[]; assets: FinanceAsset[]; inventory: InventoryItem[]; summary: FinanceSummary }) {
  const [tab, setTab] = useState<"cash" | "pockets" | "assets" | "stock" | "report">("cash");
  const [busy, setBusy] = useState(false);
  const [cash, setCash] = useState({ type: "expense" as "income" | "expense", category: "Belanja stok", amount: "", occurred_on: today(), note: "", pocket_id: "" });
  const [pocket, setPocket] = useState({ name: "", allocation_pct: "" });
  const [asset, setAsset] = useState({ name: "", category: "Peralatan", acquired_on: today(), purchase_cost: "", salvage_value: "0", useful_life_months: "36" });
  const [item, setItem] = useState({ sku: "", name: "", unit: "pcs", reorder_level: "0" });
  const [purchase, setPurchase] = useState({ supplier_name: "", purchased_on: today(), note: "", inventory_item_id: "", qty: "", unit_cost: "" });
  const [adjustment, setAdjustment] = useState({ inventory_item_id: "", delta_qty: "", reason: "" });
  const allocation = pockets.reduce((sum, value) => sum + Number(value.allocation_pct), 0);
  const lowStock = inventory.filter((value) => Number(value.stock_qty) <= Number(value.reorder_level));
  const monthlyDepreciation = useMemo(() => assets.filter((value) => value.is_active).reduce((sum, value) => sum + (Number(value.purchase_cost) - Number(value.salvage_value)) / Number(value.useful_life_months), 0), [assets]);

  const run = async (action: () => Promise<{ ok: boolean; error?: string }>) => { setBusy(true); const result = await action(); setBusy(false); if (!result.ok) alert(result.error); else window.location.reload(); };
  const submitCash = () => run(() => createFinanceTransactionAction({ ...cash, amount: Number(cash.amount), pocket_id: cash.pocket_id || null }));
  const submitPocket = () => run(() => saveFinancePocketAction({ name: pocket.name, allocation_pct: Number(pocket.allocation_pct) }));
  const submitAsset = () => run(() => saveFinanceAssetAction({ ...asset, purchase_cost: Number(asset.purchase_cost), salvage_value: Number(asset.salvage_value), useful_life_months: Number(asset.useful_life_months), is_active: true }));
  const submitItem = () => run(() => saveInventoryItemAction({ ...item, sku: item.sku || null, reorder_level: Number(item.reorder_level) }));
  const submitPurchase = () => run(() => recordInventoryPurchaseAction({ supplier_name: purchase.supplier_name, purchased_on: purchase.purchased_on, note: purchase.note, items: [{ inventory_item_id: purchase.inventory_item_id, qty: Number(purchase.qty), unit_cost: Number(purchase.unit_cost) }] }));
  const submitAdjustment = () => run(() => adjustInventoryStockAction(adjustment.inventory_item_id, Number(adjustment.delta_qty), adjustment.reason));

  return <div className="min-h-screen bg-[#f7f6fc] text-[#232331] font-sans">
    <header className="sticky top-0 z-30 border-b-2 border-[#232331] bg-white/95 px-3 py-2.5 backdrop-blur-md sm:px-6"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-2"><Link href="/app/finance" className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-[#232331] bg-white" title="Kembali ke HPP"><ArrowLeft size={16} /></Link><div className="min-w-0"><h1 className="truncate text-sm font-extrabold sm:text-base">Keuangan Usaha</h1><p className="truncate font-mono text-[10px] text-[#7b7b8e]">{business?.name} · Bulan berjalan</p></div></div><Link href="/app/finance" className="min-h-9 rounded-lg border border-[#232331] px-3 py-2 text-xs font-bold">HPP & Harga</Link></div></header>
    <main className="mx-auto w-full max-w-6xl space-y-4 p-3 sm:p-6">
      <section className="grid grid-cols-2 gap-2.5 sm:grid-cols-4"><Metric label="Omzet POS" value={formatRupiah(summary.posRevenue)} icon={<TrendingUp size={15}/>} color="text-[#166534]"/><Metric label="Kas masuk manual" value={formatRupiah(summary.income)} icon={<WalletCards size={15}/>} color="text-[#7958d8]"/><Metric label="Kas keluar" value={formatRupiah(summary.expenses)} icon={<TrendingDown size={15}/>} color="text-[#b91c1c]"/><Metric label="Hasil bulan ini" value={formatRupiah(summary.netProfit)} icon={<Calculator size={15}/>} color={summary.netProfit >= 0 ? "text-[#166534]" : "text-[#b91c1c]"}/></section>
      <nav className="flex gap-1 overflow-x-auto rounded-xl border border-[#232331] bg-white p-1 font-mono text-xs font-bold">{([['cash','Kas',<ReceiptText size={14}/>],['pockets','Kantong',<WalletCards size={14}/>],['assets','Aset',<BriefcaseBusiness size={14}/>],['stock','Stok',<Package size={14}/>],['report','Laporan',<Landmark size={14}/>]] as const).map(([key,label,icon])=><button key={key} onClick={()=>setTab(key)} className={`flex min-h-10 shrink-0 items-center gap-1.5 rounded-lg px-3 ${tab===key?'bg-[#232331] text-[#d9ff57]':'text-[#5c5c70]'}`}>{icon}{label}</button>)}</nav>
      {tab === 'cash' && <section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><Panel title="Catat uang masuk/keluar" subtitle="Gunakan untuk transaksi di luar POS."><div className="grid grid-cols-2 gap-2"><Select value={cash.type} onChange={v=>setCash({...cash,type:v as typeof cash.type})} options={[['expense','Uang keluar'],['income','Uang masuk']]}/><Input value={cash.occurred_on} onChange={v=>setCash({...cash,occurred_on:v})} type="date"/></div><Input value={cash.category} onChange={v=>setCash({...cash,category:v})} placeholder="Kategori, misal: Sewa"/><Input value={cash.amount} onChange={v=>setCash({...cash,amount:v})} type="number" placeholder="Nominal Rupiah"/><Select value={cash.pocket_id} onChange={v=>setCash({...cash,pocket_id:v})} options={[['','Tanpa kantong'],...pockets.map(v=>[v.id,v.name] as [string,string])]}/><Input value={cash.note} onChange={v=>setCash({...cash,note:v})} placeholder="Catatan (opsional)"/><Button onClick={submitCash} busy={busy}>Simpan transaksi</Button></Panel><Panel title="Buku kas terbaru" subtitle="100 transaksi terakhir."><div className="divide-y divide-[#dedee8]">{transactions.map(v=><div key={v.id} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="truncate text-sm font-bold">{v.category}</p><p className="text-[11px] text-[#7b7b8e]">{formatBusinessDate(v.occurred_on)} · {v.note || 'Tanpa catatan'}</p></div><b className={v.type==='income'?'text-[#166534]':'text-[#b91c1c]'}>{v.type==='income'?'+':'-'}{formatRupiah(v.amount)}</b></div>)}{!transactions.length&&<Empty text="Belum ada transaksi manual."/>}</div></Panel></section>}
      {tab === 'pockets' && <section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><Panel title="Tambah kantong uang" subtitle={`Total alokasi saat ini ${allocation.toFixed(0)}%.`}><Input value={pocket.name} onChange={v=>setPocket({...pocket,name:v})} placeholder="Contoh: Modal belanja"/><Input value={pocket.allocation_pct} onChange={v=>setPocket({...pocket,allocation_pct:v})} type="number" placeholder="Alokasi persen"/><Button onClick={submitPocket} busy={busy}>Tambah kantong</Button></Panel><Panel title="Pembagian uang masuk" subtitle="Panduan alokasi, bukan pemindahan bank otomatis."><div className="grid gap-2 sm:grid-cols-2">{pockets.map(v=><div key={v.id} className="rounded-xl border border-[#dedee8] bg-[#fcfcfe] p-3"><p className="font-bold">{v.name}</p><p className="mt-1 font-mono text-lg font-black text-[#7958d8]">{Number(v.allocation_pct)}%</p><p className="text-[11px] text-[#7b7b8e]">Dari uang masuk manual dan POS yang owner alokasikan.</p></div>)}{!pockets.length&&<Empty text="Buat kantong untuk modal, operasional, gaji, pajak, dan profit."/>}</div></Panel></section>}
      {tab === 'assets' && <section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><Panel title="Catat aset" subtitle="Penyusutan memakai metode garis lurus."><Input value={asset.name} onChange={v=>setAsset({...asset,name:v})} placeholder="Nama aset, misal: Mesin jahit"/><Input value={asset.category} onChange={v=>setAsset({...asset,category:v})} placeholder="Kategori"/><div className="grid grid-cols-2 gap-2"><Input value={asset.acquired_on} onChange={v=>setAsset({...asset,acquired_on:v})} type="date"/><Input value={asset.useful_life_months} onChange={v=>setAsset({...asset,useful_life_months:v})} type="number" placeholder="Masa manfaat bulan"/></div><div className="grid grid-cols-2 gap-2"><Input value={asset.purchase_cost} onChange={v=>setAsset({...asset,purchase_cost:v})} type="number" placeholder="Harga beli"/><Input value={asset.salvage_value} onChange={v=>setAsset({...asset,salvage_value:v})} type="number" placeholder="Nilai sisa"/></div><Button onClick={submitAsset} busy={busy}>Simpan aset</Button></Panel><Panel title="Aset aktif" subtitle={`Estimasi penyusutan ${formatRupiah(monthlyDepreciation)}/bulan.`}><div className="divide-y divide-[#dedee8]">{assets.map(v=><div key={v.id} className="flex items-center justify-between gap-3 py-3"><div><p className="font-bold">{v.name}</p><p className="text-[11px] text-[#7b7b8e]">{v.category} · {v.useful_life_months} bulan</p></div><b className="text-[#7958d8]">{formatRupiah((Number(v.purchase_cost)-Number(v.salvage_value))/Number(v.useful_life_months))}/bln</b></div>)}{!assets.length&&<Empty text="Belum ada aset tercatat."/>}</div></Panel></section>}
      {tab === 'stock' && <section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><Panel title="Tambah barang stok" subtitle="Untuk retail, bahan, atau barang yang dibeli ulang."><Input value={item.name} onChange={v=>setItem({...item,name:v})} placeholder="Nama barang"/><div className="grid grid-cols-2 gap-2"><Input value={item.sku} onChange={v=>setItem({...item,sku:v})} placeholder="SKU (opsional)"/><Input value={item.unit} onChange={v=>setItem({...item,unit:v})} placeholder="Satuan"/></div><Input value={item.reorder_level} onChange={v=>setItem({...item,reorder_level:v})} type="number" placeholder="Stok minimum"/><Button onClick={submitItem} busy={busy}>Simpan barang</Button><hr className="border-[#dedee8]"/><p className="text-sm font-extrabold">Catat belanja stok</p><Select value={purchase.inventory_item_id} onChange={v=>setPurchase({...purchase,inventory_item_id:v})} options={[['','Pilih barang'],...inventory.map(v=>[v.id,v.name] as [string,string])]}/><div className="grid grid-cols-2 gap-2"><Input value={purchase.qty} onChange={v=>setPurchase({...purchase,qty:v})} type="number" placeholder="Jumlah"/><Input value={purchase.unit_cost} onChange={v=>setPurchase({...purchase,unit_cost:v})} type="number" placeholder="Modal/unit"/></div><Input value={purchase.supplier_name} onChange={v=>setPurchase({...purchase,supplier_name:v})} placeholder="Supplier (opsional)"/><Input value={purchase.purchased_on} onChange={v=>setPurchase({...purchase,purchased_on:v})} type="date"/><Button onClick={submitPurchase} busy={busy}>Catat pembelian</Button><hr className="border-[#dedee8]"/><p className="text-sm font-extrabold">Penyesuaian stok</p><Select value={adjustment.inventory_item_id} onChange={v=>setAdjustment({...adjustment,inventory_item_id:v})} options={[['','Pilih barang'],...inventory.map(v=>[v.id,v.name] as [string,string])]}/><div className="grid grid-cols-2 gap-2"><Input value={adjustment.delta_qty} onChange={v=>setAdjustment({...adjustment,delta_qty:v})} type="number" placeholder="Contoh: -2"/><Input value={adjustment.reason} onChange={v=>setAdjustment({...adjustment,reason:v})} placeholder="Alasan, misal rusak"/></div><Button onClick={submitAdjustment} busy={busy}>Simpan penyesuaian</Button></Panel><Panel title="Stok sekarang" subtitle={lowStock.length?`${lowStock.length} barang perlu dibeli ulang.`:'Semua stok di atas batas minimum.'}><div className="divide-y divide-[#dedee8]">{inventory.map(v=><div key={v.id} className="flex items-center justify-between gap-3 py-3"><div><p className="font-bold">{v.name}</p><p className="text-[11px] text-[#7b7b8e]">Modal rata-rata {formatRupiah(v.average_cost)}/{v.unit} · min. {v.reorder_level}</p></div><b className={Number(v.stock_qty)<=Number(v.reorder_level)?'text-[#b91c1c]':'text-[#166534]'}>{v.stock_qty} {v.unit}</b></div>)}{!inventory.length&&<Empty text="Tambahkan barang sebelum mencatat pembelian."/>}</div></Panel></section>}
      {tab === 'report' && <section className="grid gap-4 lg:grid-cols-2"><Panel title="Laba rugi bulan berjalan" subtitle="HPP hanya dihitung pada menu POS yang sudah dipetakan ke resep."><Rows rows={[["Omzet dari POS",summary.posRevenue],["HPP terpetakan",-summary.estimatedCogs],["Laba kotor estimasi",summary.grossProfit],["Pendapatan lain",summary.income],["Beban operasional",-summary.operatingExpenses],["Penyusutan aset",-summary.depreciation],["Laba bersih estimasi",summary.netProfit]]}/><p className="border-t border-[#dedee8] pt-3 text-[11px] text-[#7b7b8e]">Cakupan HPP: {formatRupiah(summary.hppCoverageRevenue)} dari omzet POS. Pembelian stok tetap terlihat sebagai kas keluar, tidak langsung dibebankan sebelum stok terjual.</p></Panel><Panel title="Target balik modal" subtitle="Target minimal untuk menutup biaya tetap dan penyusutan bulan ini."><p className="font-mono text-3xl font-black text-[#7958d8]">{formatRupiah(summary.breakEvenRevenue)}</p><p className="mt-2 text-xs leading-5 text-[#5c5c70]">Tambahkan target margin di HPP untuk mengubah target ini menjadi target unit per produk. Angka makin presisi saat semua menu POS dipetakan ke resep.</p><Link href="/app/pos/reports" className="mt-4 inline-flex min-h-11 items-center rounded-lg border border-[#232331] px-3 text-xs font-bold">Buka laporan POS</Link></Panel></section>}
    </main></div>;
}
function Input({value,onChange,placeholder='',type='text'}:{value:string;onChange:(v:string)=>void;placeholder?:string;type?:string}){return <input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} type={type} className="min-h-11 w-full rounded-lg border border-[#232331] bg-white px-3 text-sm font-semibold"/>}
function Select({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:[string,string][]}){return <select value={value} onChange={e=>onChange(e.target.value)} className="min-h-11 w-full rounded-lg border border-[#232331] bg-white px-3 text-sm font-semibold">{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>}
function Button({onClick,busy,children}:{onClick:()=>void;busy:boolean;children:React.ReactNode}){return <button type="button" onClick={onClick} disabled={busy} className="btn-tactile min-h-11 w-full rounded-lg border border-[#232331] bg-[#232331] px-3 text-xs font-black text-[#d9ff57] disabled:opacity-50"><Plus size={14} className="mr-1 inline"/>{busy?'Menyimpan...':children}</button>}
function Panel({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="rounded-2xl border-2 border-[#232331] bg-white p-4 shadow-ink-md sm:p-5"><div className="border-b border-[#dedee8] pb-3"><h2 className="text-sm font-extrabold">{title}</h2><p className="mt-1 text-xs text-[#5c5c70]">{subtitle}</p></div><div className="mt-4 space-y-3">{children}</div></div>}
function Metric({label,value,icon,color}:{label:string;value:string;icon:React.ReactNode;color:string}){return <div className="rounded-xl border border-[#232331] bg-white p-3"><div className={`flex items-center justify-between ${color}`}><span className="font-mono text-[9px] font-bold uppercase">{label}</span>{icon}</div><p className="mt-2 truncate font-mono text-sm font-black text-[#232331] sm:text-lg">{value}</p></div>}
function Rows({rows}:{rows:[string,number][]}){return <div className="space-y-3">{rows.map(([label,value],i)=><div key={label} className={`flex justify-between text-sm ${i===rows.length-1?'border-t-2 border-[#232331] pt-3 font-black':'text-[#5c5c70]'}`}><span>{label}</span><span className={value<0?'text-[#b91c1c]':'text-[#232331]'}>{value<0?'-':''}{formatRupiah(Math.abs(value))}</span></div>)}</div>}
function Empty({text}:{text:string}){return <p className="py-6 text-center text-xs text-[#7b7b8e]">{text}</p>}
