import Link from "next/link";

import { db } from "@/lib/db";
import { guardOwnerPage } from "@/lib/licensing";

function isoDate(days: number) { return new Date(Date.now() + days * 86_400_000).toISOString().slice(0, 10); }
const money = (value: number) => `Rp ${Number(value).toLocaleString("id-ID")}`;

export default async function FinanceReportsPage() {
  const session = await guardOwnerPage("/app/finance/reports");
  const from = isoDate(-30); const to = isoDate(0);
  const [report, payables] = await Promise.all([db.getFormalFinanceReport(session.businessId, from, to), db.getPayables(session.businessId)]);
  return <main className="min-h-screen bg-[#f7f6fc] p-4 text-[#232331] sm:p-8"><div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-wrap justify-between gap-3"><div><p className="font-mono text-[11px] font-bold text-[#7958d8]">KAEL FINANCE</p><h1 className="text-2xl font-black">Laporan formal 30 hari</h1><p className="mt-1 text-sm text-[#66667a]">{from} sampai {to}. Angka berasal dari POS, transaksi finance, stok, dan hutang supplier.</p></div><Link href="/app/finance" className="rounded-lg border-2 border-[#232331] bg-white px-3 py-2 text-sm font-bold">Kembali</Link></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Pendapatan" value={money(report.income)} /><Metric label="HPP tercatat" value={money(report.cogs)} /><Metric label="Laba bersih" value={money(report.netProfit)} good={report.netProfit >= 0} /><Metric label="Arus kas" value={money(report.cashFlow)} good={report.cashFlow >= 0} /></section><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><h2 className="font-bold">Laba rugi</h2><dl className="mt-4 space-y-3 text-sm"><Line label="Pendapatan" value={report.income}/><Line label="HPP" value={-report.cogs}/><Line label="Laba kotor" value={report.grossProfit} strong/><Line label="Beban usaha" value={-report.expenses}/><Line label="Laba bersih" value={report.netProfit} strong/></dl></section><section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><h2 className="font-bold">Neraca ringkas</h2><dl className="mt-4 space-y-3 text-sm"><Line label="Aset tetap bersih" value={report.balanceSheet.assets}/><Line label="Hutang usaha" value={-report.balanceSheet.liabilities}/><Line label="Ekuitas bersih" value={report.balanceSheet.equity} strong/></dl><p className="mt-4 text-xs text-[#66667a]">Ekspor akuntansi memakai struktur kategori dan pajak di transaksi finance. Integrasi jurnal ke software akuntansi bisa ditambahkan pada kanal ekspor tenant.</p></section></div><section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><h2 className="font-bold">Hutang supplier</h2>{payables.length ? <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b"><tr><th className="p-2">Supplier</th><th className="p-2">Tagihan</th><th className="p-2">Jatuh tempo</th><th className="p-2 text-right">Sisa</th></tr></thead><tbody>{payables.map((item) => <tr key={item.id as string} className="border-b border-[#eee]" ><td className="p-2 font-bold">{item.supplier_name as string}</td><td className="p-2">{item.bill_no as string}</td><td className="p-2">{String(item.due_on ?? "-")}</td><td className="p-2 text-right">{money(Number(item.total_amount) - Number(item.paid_amount))}</td></tr>)}</tbody></table></div> : <p className="mt-3 text-sm text-[#66667a]">Tidak ada hutang supplier terbuka.</p>}</section></div></main>;
}
function Metric({ label, value, good }: { label: string; value: string; good?: boolean }) { return <div className="rounded-2xl border-2 border-[#232331] bg-white p-4 shadow-ink-md"><p className="font-mono text-[10px] font-bold text-[#7958d8]">{label}</p><p className={`mt-2 text-xl font-black ${good === false ? "text-[#c2410c]" : ""}`}>{value}</p></div>; }
function Line({ label, value, strong }: { label: string; value: number; strong?: boolean }) { return <div className={`flex justify-between border-b border-[#eee] pb-2 ${strong ? "font-black" : ""}`}><dt>{label}</dt><dd>{value < 0 ? `(${money(Math.abs(value))})` : money(value)}</dd></div>; }
