"use client";

import { useState } from "react";
import { Clock3, MapPinned, Pencil, Plus, Power, Trash2 } from "lucide-react";
import { deleteDeliveryZoneAction, saveDeliveryZoneAction, saveOrderingSettingsAction } from "@/lib/actions-operations";

type Settings = { is_open: boolean; minimum_order: number; opens_at: string | null; closes_at: string | null; delivery_enabled: boolean; pickup_enabled: boolean } | null;
type Zone = { id: string; name: string; postal_codes: string[]; fee: number; minimum_order: number; is_active: boolean };
type Notice = { tone: "success" | "error"; text: string } | null;

export default function OrderingClient({ initial, themeClassName = "" }: { initial: { settings: Settings; zones: Zone[] }; themeClassName?: string }) {
  const setting = initial.settings; const [open, setOpen] = useState(setting?.is_open ?? true); const [minimum, setMinimum] = useState(String(setting?.minimum_order ?? 0)); const [delivery, setDelivery] = useState(setting?.delivery_enabled ?? false); const [pickup, setPickup] = useState(setting?.pickup_enabled ?? true); const [opensAt, setOpensAt] = useState(setting?.opens_at?.slice(0, 5) ?? ""); const [closesAt, setClosesAt] = useState(setting?.closes_at?.slice(0, 5) ?? "");
  const [zone, setZone] = useState({ id: "", name: "", postal: "", fee: "0", minimum: "0", active: true }); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<Notice>(null);
  const run = async (action: () => Promise<{ ok: boolean; error?: string }>, success: string) => { setSaving(true); const result = await action(); setSaving(false); setNotice(result.ok ? { tone: "success", text: success } : { tone: "error", text: result.error || "Perubahan belum tersimpan." }); if (result.ok) window.location.reload(); };
  const saveRules = () => run(() => saveOrderingSettingsAction({ isOpen: open, minimumOrder: Number(minimum), opensAt: opensAt || undefined, closesAt: closesAt || undefined, deliveryEnabled: delivery, pickupEnabled: pickup }), "Aturan pesanan online disimpan.");
  const saveZone = () => run(() => saveDeliveryZoneAction({ id: zone.id || undefined, name: zone.name, postalCodes: zone.postal, fee: Number(zone.fee), minimumOrder: Number(zone.minimum), active: zone.active }), zone.id ? "Area delivery diperbarui." : "Area delivery ditambahkan.");
  const edit = (item: Zone) => setZone({ id: item.id, name: item.name, postal: item.postal_codes.join(", "), fee: String(item.fee), minimum: String(item.minimum_order), active: item.is_active });
  return <main className={`${themeClassName} mochi-shell min-h-screen bg-[#f7f6fc] p-4 pb-24 text-[#232331] sm:p-8`}><div className="mx-auto max-w-5xl space-y-5"><header><p className="font-mono text-[11px] font-bold text-[#7958d8]">KAEL ORDERING</p><h1 className="text-2xl font-black">Aturan pesan online</h1><p className="mt-1 text-sm text-[#66667a]">Atur kapan order masuk, cara pelanggan menerima pesanan, serta ongkir tiap area.</p></header>{notice && <div role="status" className={`rounded-xl border p-3 text-sm font-bold ${notice.tone === "success" ? "border-[#15803d] bg-[#dcfce7] text-[#166534]" : "border-[#b91c1c] bg-[#fef2f2] text-[#b91c1c]"}`}>{notice.text}</div>}
    <section className="grid gap-4 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="flex items-center gap-2"><Power size={18} /><h2 className="font-black">Status dan jam buka</h2></div><div className="mt-4 space-y-3"><Switch label="Terima pesanan sekarang" checked={open} onChange={setOpen} /><Switch label="Pickup tersedia" checked={pickup} onChange={setPickup} /><Switch label="Delivery tersedia" checked={delivery} onChange={setDelivery} /><label className="block text-xs font-bold">Minimum order seluruh toko (Rp)<input type="number" min="0" value={minimum} onChange={(event) => setMinimum(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-[#232331] p-2" /></label><div className="grid grid-cols-2 gap-2"><label className="text-xs font-bold">Buka<input type="time" value={opensAt} onChange={(event) => setOpensAt(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-[#232331] p-2" /></label><label className="text-xs font-bold">Tutup<input type="time" value={closesAt} onChange={(event) => setClosesAt(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-[#232331] p-2" /></label></div><p className="inline-flex items-start gap-1.5 text-xs leading-5 text-[#66667a]"><Clock3 size={14} className="mt-0.5 shrink-0" />Kosongkan dua jam bila toko menerima order sepanjang hari.</p><button type="button" disabled={saving} onClick={saveRules} className="min-h-11 w-full rounded-xl border-2 border-[#232331] bg-[#d9ff57] text-sm font-black disabled:opacity-50">Simpan aturan</button></div></div>
      <form onSubmit={(event) => { event.preventDefault(); saveZone(); }} className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="flex items-center gap-2"><MapPinned size={18} /><h2 className="font-black">{zone.id ? "Ubah area delivery" : "Tambah area delivery"}</h2></div><p className="mt-2 text-xs leading-5 text-[#66667a]">Kode pos membantu kasir mengecek jangkauan. Minimum order di sini menggantikan minimum order toko.</p><label className="mt-3 block text-xs font-bold">Nama area<input required value={zone.name} onChange={(event) => setZone({ ...zone, name: event.target.value })} placeholder="Contoh: Padang Panjang pusat" className="mt-1 min-h-11 w-full rounded-lg border border-[#232331] p-2" /></label><label className="mt-3 block text-xs font-bold">Kode pos (pisahkan dengan koma)<input value={zone.postal} onChange={(event) => setZone({ ...zone, postal: event.target.value })} placeholder="27111, 27112" className="mt-1 min-h-11 w-full rounded-lg border border-[#232331] p-2" /></label><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-xs font-bold">Ongkir (Rp)<input type="number" min="0" value={zone.fee} onChange={(event) => setZone({ ...zone, fee: event.target.value })} className="mt-1 min-h-11 w-full rounded-lg border border-[#232331] p-2" /></label><label className="text-xs font-bold">Minimum order area (Rp)<input type="number" min="0" value={zone.minimum} onChange={(event) => setZone({ ...zone, minimum: event.target.value })} className="mt-1 min-h-11 w-full rounded-lg border border-[#232331] p-2" /></label></div><Switch label="Area ini aktif" checked={zone.active} onChange={(active) => setZone({ ...zone, active })} /><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={saving} className="min-h-11 rounded-xl border-2 border-[#232331] bg-[#7958d8] text-sm font-black text-white disabled:opacity-50">{zone.id ? "Simpan perubahan" : "Tambah area"}</button><button type="button" onClick={() => setZone({ id: "", name: "", postal: "", fee: "0", minimum: "0", active: true })} className="min-h-11 rounded-xl border border-[#232331] bg-white text-sm font-bold">Batal</button></div></form></section>
    <section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><h2 className="font-black">Area delivery yang tersimpan</h2><div className="mt-3 space-y-2">{initial.zones.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#dedee8] p-3"><div><p className="font-bold">{item.name} {!item.is_active && <span className="ml-1 text-xs text-[#b91c1c]">Nonaktif</span>}</p><p className="mt-1 text-xs text-[#66667a]">{item.postal_codes.join(", ") || "Tanpa batas kode pos"} · Ongkir Rp {Number(item.fee).toLocaleString("id-ID")} · Min. Rp {Number(item.minimum_order).toLocaleString("id-ID")}</p></div><div className="flex gap-2"><button type="button" onClick={() => edit(item)} className="inline-flex min-h-10 items-center gap-1 rounded-lg border border-[#232331] px-3 text-xs font-bold"><Pencil size={13} />Ubah</button><button type="button" onClick={() => run(() => deleteDeliveryZoneAction(item.id), "Area delivery dihapus.")} className="inline-flex min-h-10 items-center gap-1 rounded-lg border border-[#b91c1c] px-3 text-xs font-bold text-[#b91c1c]"><Trash2 size={13} />Hapus</button></div></div>)}{!initial.zones.length && <p className="rounded-xl bg-[#f7f6fc] p-4 text-sm text-[#66667a]">Belum ada area delivery. Pickup tetap bisa dipakai bila diaktifkan.</p>}</div></section>
  </div></main>;
}
function Switch({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex min-h-11 items-center justify-between gap-3 rounded-xl border border-[#dedee8] p-3 text-sm font-bold"><span>{label}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /></label>; }
