"use client";

import { useState } from "react";
import { CalendarDays, Check, Clock3, Copy, Link2, Plus, Send, UsersRound, X } from "lucide-react";
import { deleteBookingScheduleAction, saveBookingScheduleAction, saveBookingServiceAction, updateBookingStatusAction } from "@/lib/actions-operations";

type Service = { id: string; name: string; duration_minutes: number; price: number; deposit_amount: number; capacity: number; is_active: boolean };
type Appointment = { id: string; customer_name: string; customer_phone: string; starts_at: string; ends_at: string; status: "pending_deposit" | "confirmed" | "completed" | "cancelled" | "no_show"; deposit_amount: number; deposit_status: string; service_name: string; staff_name: string | null };
type Schedule = { id: string; user_id: string | null; day_of_week: number; starts_at: string; ends_at: string; slot_interval_minutes: number; staff_name: string | null };
type Waitlist = { id: string; customer_name: string; customer_phone: string; preferred_start: string | null; service_name: string; status: string };
type Reminder = { id: string; customer_name: string; customer_phone: string; starts_at: string; service_name: string; scheduled_for: string };
type Notice = { tone: "success" | "error"; text: string } | null;
const days = ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"];

export default function BookingClient({ data, storeCode }: { data: { services: Service[]; appointments: Appointment[]; staff: { id: string; name: string }[]; schedules: Schedule[]; waitlist: Waitlist[]; reminders: Reminder[]; insights: { total: number; completed: number; noShow: number; noShowRate: number } }; storeCode: string }) {
  const [service, setService] = useState({ name: "", duration: "30", price: "0", deposit: "0", capacity: "1" });
  const [schedule, setSchedule] = useState({ staffId: "", day: "1", start: "09:00", end: "17:00", interval: "30" });
  const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<Notice>(null);
  const run = async (action: () => Promise<{ ok: boolean; error?: string }>, success: string) => { setSaving(true); const result = await action(); setSaving(false); setNotice(result.ok ? { tone: "success", text: success } : { tone: "error", text: result.error || "Perubahan belum tersimpan." }); if (result.ok) window.location.reload(); };
  const publicUrl = typeof window === "undefined" ? `/booking/${storeCode}` : `${window.location.origin}/booking/${storeCode}`;
  const copy = async () => { await navigator.clipboard.writeText(publicUrl); setNotice({ tone: "success", text: "Tautan booking publik disalin." }); };
  const whatsapp = (item: Reminder | Waitlist) => `https://wa.me/${item.customer_phone.replace(/\D/g, "")}?text=${encodeURIComponent(`Halo ${item.customer_name}, ada kabar dari ${item.service_name}.`)}`;
  return <main className="min-h-screen bg-[#f7f6fc] p-4 pb-24 text-[#232331] sm:p-8"><div className="mx-auto max-w-6xl space-y-5">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-[11px] font-bold text-[#7958d8]">KAEL BOOKING</p><h1 className="text-2xl font-black">Booking yang siap dibagikan</h1><p className="mt-1 text-sm text-[#66667a]">Susun layanan dan jam slot, lalu customer booking sendiri lewat tautan publik.</p></div><button type="button" onClick={copy} className="inline-flex min-h-11 items-center gap-2 rounded-xl border-2 border-[#232331] bg-[#d9ff57] px-3 text-sm font-black"><Link2 size={16} />Salin link booking</button></header>
    {notice && <div role="status" className={`rounded-xl border p-3 text-sm font-bold ${notice.tone === "success" ? "border-[#15803d] bg-[#dcfce7] text-[#166534]" : "border-[#b91c1c] bg-[#fef2f2] text-[#b91c1c]"}`}>{notice.text}</div>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Booking tercatat" value={data.insights.total} /><Metric label="Selesai" value={data.insights.completed} /><Metric label="No-show" value={data.insights.noShow} detail={`${data.insights.noShowRate}% dari total`} /><Metric label="Waitlist" value={data.waitlist.length} /></section>
    <section className="grid gap-4 lg:grid-cols-[.85fr_1.15fr]"><form onSubmit={(event) => { event.preventDefault(); run(() => saveBookingServiceAction({ name: service.name, durationMinutes: Number(service.duration), price: Number(service.price), depositAmount: Number(service.deposit), capacity: Number(service.capacity), active: true }), "Layanan booking disimpan."); }} className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="flex items-center gap-2"><Plus size={18} /><h2 className="font-black">Tambah layanan</h2></div><p className="mt-2 text-xs leading-5 text-[#66667a]">Isi harga dan DP bila pembayaran masih dikonfirmasi manual oleh owner.</p><label className="mt-3 block text-xs font-bold">Nama layanan<input required value={service.name} onChange={(event) => setService({ ...service, name: event.target.value })} placeholder="Contoh: Potong rambut" className="mt-1 min-h-11 w-full rounded-lg border border-[#232331] p-2" /></label><div className="mt-3 grid grid-cols-2 gap-2"><Field label="Durasi menit" value={service.duration} onChange={(value) => setService({ ...service, duration: value })} min="5" /><Field label="Kapasitas tiap slot" value={service.capacity} onChange={(value) => setService({ ...service, capacity: value })} min="1" /></div><div className="mt-3 grid grid-cols-2 gap-2"><Field label="Harga (Rp)" value={service.price} onChange={(value) => setService({ ...service, price: value })} min="0" /><Field label="DP (Rp)" value={service.deposit} onChange={(value) => setService({ ...service, deposit: value })} min="0" /></div><button disabled={saving} className="mt-4 min-h-11 w-full rounded-xl border-2 border-[#232331] bg-[#7958d8] text-sm font-black text-white disabled:opacity-50">Simpan layanan</button></form>
      <div className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><h2 className="font-black">Layanan aktif</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{data.services.map((item) => <div key={item.id} className="rounded-xl border border-[#dedee8] p-3"><p className="font-bold">{item.name}</p><p className="mt-1 text-xs text-[#66667a]">{item.duration_minutes} menit · kapasitas {item.capacity}</p><p className="mt-1 font-mono text-xs font-bold">Rp {Number(item.price).toLocaleString("id-ID")} · DP Rp {Number(item.deposit_amount).toLocaleString("id-ID")}</p></div>)}{!data.services.length && <p className="text-sm text-[#66667a]">Tambahkan layanan pertama sebelum link publik dibagikan.</p>}</div></div></section>
    <section className="grid gap-4 lg:grid-cols-[.85fr_1.15fr]"><form onSubmit={(event) => { event.preventDefault(); run(() => saveBookingScheduleAction({ userId: schedule.staffId || undefined, dayOfWeek: Number(schedule.day), startsAt: schedule.start, endsAt: schedule.end, intervalMinutes: Number(schedule.interval), active: true }), "Jam slot booking disimpan."); }} className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="flex items-center gap-2"><Clock3 size={18} /><h2 className="font-black">Jam slot booking</h2></div><label className="mt-3 block text-xs font-bold">Staf (opsional)<select value={schedule.staffId} onChange={(event) => setSchedule({ ...schedule, staffId: event.target.value })} className="mt-1 min-h-11 w-full rounded-lg border border-[#232331] p-2"><option value="">Semua staf / kapasitas layanan</option>{data.staff.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-xs font-bold">Hari<select value={schedule.day} onChange={(event) => setSchedule({ ...schedule, day: event.target.value })} className="mt-1 min-h-11 w-full rounded-lg border border-[#232331] p-2">{days.map((day, index) => <option key={day} value={index}>{day}</option>)}</select></label><Field label="Interval menit" value={schedule.interval} onChange={(value) => setSchedule({ ...schedule, interval: value })} min="5" /></div><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-xs font-bold">Mulai<input type="time" value={schedule.start} onChange={(event) => setSchedule({ ...schedule, start: event.target.value })} className="mt-1 min-h-11 w-full rounded-lg border border-[#232331] p-2" /></label><label className="text-xs font-bold">Selesai<input type="time" value={schedule.end} onChange={(event) => setSchedule({ ...schedule, end: event.target.value })} className="mt-1 min-h-11 w-full rounded-lg border border-[#232331] p-2" /></label></div><button disabled={saving} className="mt-4 min-h-11 w-full rounded-xl border-2 border-[#232331] bg-[#d9ff57] text-sm font-black">Simpan jam slot</button></form>
      <div className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><h2 className="font-black">Slot yang dibuka</h2><div className="mt-3 space-y-2">{data.schedules.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-[#dedee8] p-3 text-sm"><span><b>{days[item.day_of_week]}</b> · {item.starts_at.slice(0, 5)}-{item.ends_at.slice(0, 5)} · {item.slot_interval_minutes} menit</span><span className="flex items-center gap-2"><em className="text-xs not-italic text-[#66667a]">{item.staff_name || "Semua staf"}</em><button type="button" onClick={() => run(() => deleteBookingScheduleAction(item.id), "Jam slot dihapus.")} className="min-h-9 rounded-lg border border-[#b91c1c] px-2 text-xs font-bold text-[#b91c1c]">Hapus</button></span></div>)}{!data.schedules.length && <p className="rounded-xl bg-[#fff7ed] p-3 text-sm text-[#9a3412]">Belum ada jam slot. Customer belum bisa memilih waktu booking.</p>}</div></div></section>
    <section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="flex items-center gap-2"><CalendarDays size={18} /><h2 className="font-black">Kalender owner dan DP</h2></div><div className="mt-3 space-y-2">{data.appointments.map((item) => <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#dedee8] p-3"><div><p className="font-bold">{item.customer_name} <span className="font-normal text-[#66667a]">· {item.service_name}</span></p><p className="mt-1 text-xs text-[#66667a]">{new Date(item.starts_at).toLocaleString("id-ID")} · {item.staff_name || "Staf belum dipilih"}</p><p className="mt-1 font-mono text-[10px]">{item.status} · DP {item.deposit_status} {item.deposit_amount ? `Rp ${Number(item.deposit_amount).toLocaleString("id-ID")}` : ""}</p></div><div className="flex flex-wrap gap-2">{item.status === "pending_deposit" && <button type="button" onClick={() => run(() => updateBookingStatusAction(item.id, "confirmed"), "DP dikonfirmasi, booking aktif.")} className="min-h-10 rounded-lg border-2 border-[#232331] bg-[#d9ff57] px-3 text-xs font-bold">DP diterima</button>}{item.status === "confirmed" && <><button type="button" onClick={() => run(() => updateBookingStatusAction(item.id, "completed"), "Booking ditandai selesai.")} className="min-h-10 rounded-lg border-2 border-[#232331] bg-[#7958d8] px-3 text-xs font-bold text-white">Selesai</button><button type="button" onClick={() => run(() => updateBookingStatusAction(item.id, "no_show"), "Booking ditandai no-show.")} className="min-h-10 rounded-lg border border-[#b45309] px-3 text-xs font-bold text-[#9a3412]">No-show</button></>}{["pending_deposit", "confirmed"].includes(item.status) && <button type="button" onClick={() => run(() => updateBookingStatusAction(item.id, "cancelled"), "Booking dibatalkan.")} className="min-h-10 rounded-lg border border-[#b91c1c] px-3 text-xs font-bold text-[#b91c1c]"><X size={14} /></button>}</div></article>)}{!data.appointments.length && <p className="text-sm text-[#66667a]">Belum ada booking masuk.</p>}</div></section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="flex items-center gap-2"><UsersRound size={18} /><h2 className="font-black">Waiting list</h2></div><div className="mt-3 space-y-2">{data.waitlist.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border border-[#dedee8] p-3 text-sm"><div><b>{item.customer_name}</b><p className="text-xs text-[#66667a]">{item.service_name} · {item.preferred_start ? new Date(item.preferred_start).toLocaleString("id-ID") : "Waktu fleksibel"}</p></div><a href={whatsapp(item)} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center gap-1 rounded-lg border border-[#232331] px-3 text-xs font-bold"><Send size={13} />Hubungi</a></div>)}{!data.waitlist.length && <p className="text-sm text-[#66667a]">Tidak ada customer yang menunggu slot.</p>}</div></div><div className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="flex items-center gap-2"><Send size={18} /><h2 className="font-black">Reminder WhatsApp</h2></div><p className="mt-2 text-xs leading-5 text-[#66667a]">Reminder dibuat otomatis 24 jam sebelum jadwal. Saat channel WA belum terhubung, owner mengirimnya dari tombol ini.</p><div className="mt-3 space-y-2">{data.reminders.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border border-[#dedee8] p-3 text-sm"><div><b>{item.customer_name}</b><p className="text-xs text-[#66667a]">{item.service_name} · {new Date(item.starts_at).toLocaleString("id-ID")}</p></div><a href={whatsapp(item)} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center gap-1 rounded-lg border border-[#232331] px-3 text-xs font-bold"><Send size={13} />Kirim WA</a></div>)}{!data.reminders.length && <p className="text-sm text-[#66667a]">Tidak ada reminder yang jatuh tempo.</p>}</div></div></section>
  </div></main>;
}

function Metric({ label, value, detail }: { label: string; value: number; detail?: string }) { return <div className="rounded-2xl border-2 border-[#232331] bg-white p-4 shadow-ink-xs"><p className="font-mono text-[10px] font-bold text-[#7958d8]">{label}</p><p className="mt-2 text-2xl font-black">{value}</p>{detail && <p className="mt-1 text-xs text-[#66667a]">{detail}</p>}</div>; }
function Field({ label, value, onChange, min }: { label: string; value: string; onChange: (value: string) => void; min: string }) { return <label className="text-xs font-bold">{label}<input type="number" min={min} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-[#232331] p-2" /></label>; }
