"use client";

import { useState } from "react";
import { CalendarDays, Check, Clock3, Plus, X } from "lucide-react";
import { saveBookingServiceAction, updateBookingStatusAction } from "@/lib/actions-operations";

type Service = { id: string; name: string; duration_minutes: number; price: number; deposit_amount: number; capacity: number; is_active: boolean };
type Appointment = { id: string; customer_name: string; customer_phone: string; starts_at: string; ends_at: string; status: "pending_deposit" | "confirmed" | "completed" | "cancelled" | "no_show"; deposit_amount: number; deposit_status: string; service_name: string; staff_name: string | null };

export default function BookingClient({ data }: { data: { services: Service[]; appointments: Appointment[]; staff: { id: string; name: string }[] } }) {
  const [name, setName] = useState(""); const [duration, setDuration] = useState(30); const [price, setPrice] = useState(0); const [deposit, setDeposit] = useState(0); const [capacity, setCapacity] = useState(1); const [saving, setSaving] = useState(false);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); const result = await saveBookingServiceAction({ name, durationMinutes: duration, price, depositAmount: deposit, capacity, active: true }); setSaving(false); if (!result.ok) return alert(result.error); location.reload(); };
  const update = async (id: string, status: "confirmed" | "completed" | "cancelled" | "no_show") => { const result = await updateBookingStatusAction(id, status); if (!result.ok) alert(result.error); else location.reload(); };
  return <main className="min-h-screen bg-[#f7f6fc] p-4 text-[#232331] sm:p-8"><div className="mx-auto max-w-6xl space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-[11px] font-bold text-[#7958d8]">KAEL BOOKING</p><h1 className="text-2xl font-black">Jadwal, kapasitas, dan pelanggan</h1><p className="mt-1 text-sm text-[#66667a]">Booking publik akan memakai layanan yang aktif di bawah ini.</p></div><a className="rounded-lg border-2 border-[#232331] bg-[#d9ff57] px-3 py-2 text-sm font-bold" href="/app">Kembali ke Hub</a></header>
    <div className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={save} className="space-y-3 rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="flex items-center gap-2 font-bold"><Plus size={17}/>Tambah layanan</div><input required value={name} onChange={(e)=>setName(e.target.value)} placeholder="Contoh: Potong rambut" className="w-full rounded-md border border-[#232331] p-2 text-sm"/><div className="grid grid-cols-2 gap-2"><label className="text-xs font-bold">Durasi menit<input type="number" min="5" value={duration} onChange={(e)=>setDuration(Number(e.target.value))} className="mt-1 w-full rounded-md border border-[#232331] p-2"/></label><label className="text-xs font-bold">Kapasitas<input type="number" min="1" value={capacity} onChange={(e)=>setCapacity(Number(e.target.value))} className="mt-1 w-full rounded-md border border-[#232331] p-2"/></label></div><label className="block text-xs font-bold">Harga<input type="number" min="0" value={price} onChange={(e)=>setPrice(Number(e.target.value))} className="mt-1 w-full rounded-md border border-[#232331] p-2"/></label><label className="block text-xs font-bold">DP<input type="number" min="0" value={deposit} onChange={(e)=>setDeposit(Number(e.target.value))} className="mt-1 w-full rounded-md border border-[#232331] p-2"/></label><button disabled={saving} className="w-full rounded-lg border-2 border-[#232331] bg-[#7958d8] p-2 text-sm font-bold text-white disabled:opacity-50">{saving ? "Menyimpan..." : "Simpan layanan"}</button></form>
      <section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="mb-4 flex items-center gap-2"><CalendarDays size={18}/><h2 className="font-bold">Kalender owner</h2></div>{data.appointments.length === 0 ? <p className="text-sm text-[#66667a]">Belum ada booking. Aktifkan layanan lalu bagikan halaman booking publik.</p> : <div className="space-y-3">{data.appointments.map((item)=><article key={item.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-[#dedee8] pb-3"><div><p className="font-bold">{item.customer_name} <span className="font-normal text-[#66667a]">· {item.service_name}</span></p><p className="mt-1 text-xs text-[#66667a]"><Clock3 className="mr-1 inline" size={12}/>{new Date(item.starts_at).toLocaleString("id-ID")} · {item.staff_name || "Belum pilih staf"}</p><p className="mt-1 font-mono text-[10px]">{item.status} · DP {item.deposit_status}</p></div><div className="flex gap-2">{item.status === "pending_deposit" && <button onClick={()=>update(item.id,"confirmed")} className="rounded-md border border-[#232331] bg-[#d9ff57] p-2" title="Konfirmasi DP"><Check size={14}/></button>}{["pending_deposit","confirmed"].includes(item.status) && <button onClick={()=>update(item.id,"cancelled")} className="rounded-md border border-[#232331] bg-white p-2" title="Batalkan"><X size={14}/></button>}{item.status === "confirmed" && <button onClick={()=>update(item.id,"completed")} className="rounded-md border border-[#232331] bg-[#7958d8] px-2 text-xs font-bold text-white">Selesai</button>}</div></article>)}</div>}</section></div>
    <section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><h2 className="font-bold">Layanan aktif</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.services.map((item)=><div key={item.id} className="border-l-4 border-[#7958d8] bg-[#f7f6fc] p-3"><p className="font-bold">{item.name}</p><p className="mt-1 text-xs text-[#66667a]">{item.duration_minutes} menit · Rp {Number(item.price).toLocaleString("id-ID")} · DP Rp {Number(item.deposit_amount).toLocaleString("id-ID")}</p></div>)}</div></section>
  </div></main>;
}
