"use client";

import { useState } from "react";
import { CalendarClock, MapPin, ShieldCheck, UserRoundCheck } from "lucide-react";
import { saveStaffScheduleAction } from "@/lib/actions-operations";

type Staff = { id: string; name: string; role: string };
type Schedule = { id: string; user_id: string; staff_name: string; starts_at: string; ends_at: string; role_label: string | null; pos_shift_allowed: boolean; status: string };
type Attendance = { id: string; staff_name: string; check_in_at: string | null; check_out_at: string | null; method: string; status: string };

export default function HrClient({ data }: { data: { staff: Staff[]; schedules: Schedule[]; attendance: Attendance[]; sites: { id: string; name: string; qr_token: string }[] } }) {
  const [userId, setUserId] = useState(data.staff[0]?.id || ""); const [startsAt, setStartsAt] = useState(""); const [endsAt, setEndsAt] = useState(""); const [roleLabel, setRoleLabel] = useState("Kasir"); const [allowPos, setAllowPos] = useState(false); const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); const result = await saveStaffScheduleAction({ userId, startsAt: new Date(startsAt).toISOString(), endsAt: new Date(endsAt).toISOString(), roleLabel, posShiftAllowed: allowPos }); setSaving(false); if (!result.ok) alert(result.error); else location.reload(); };
  return <main className="min-h-screen bg-[#f7f6fc] p-4 text-[#232331] sm:p-8"><div className="mx-auto max-w-6xl space-y-6"><header><p className="font-mono text-[11px] font-bold text-[#7958d8]">KAEL HR</p><h1 className="text-2xl font-black">Absensi dan jadwal kerja</h1><p className="mt-1 text-sm text-[#66667a]">Jadwal yang diberi izin POS akan menjadi syarat buka shift ketika aturan itu diaktifkan pada tenant.</p></header>
    <div className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={submit} className="space-y-3 rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="flex items-center gap-2 font-bold"><CalendarClock size={18}/>Buat jadwal shift</div><label className="block text-xs font-bold">Staf<select value={userId} onChange={(e)=>setUserId(e.target.value)} className="mt-1 w-full rounded-md border border-[#232331] p-2">{data.staff.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-xs font-bold">Mulai<input required type="datetime-local" value={startsAt} onChange={(e)=>setStartsAt(e.target.value)} className="mt-1 w-full rounded-md border border-[#232331] p-2"/></label><label className="block text-xs font-bold">Selesai<input required type="datetime-local" value={endsAt} onChange={(e)=>setEndsAt(e.target.value)} className="mt-1 w-full rounded-md border border-[#232331] p-2"/></label><label className="block text-xs font-bold">Peran<input value={roleLabel} onChange={(e)=>setRoleLabel(e.target.value)} className="mt-1 w-full rounded-md border border-[#232331] p-2"/></label><label className="flex items-center gap-2 rounded-md bg-[#f0edff] p-2 text-xs font-bold"><input checked={allowPos} onChange={(e)=>setAllowPos(e.target.checked)} type="checkbox"/>Boleh buka shift POS</label><button disabled={saving || !userId} className="w-full rounded-lg border-2 border-[#232331] bg-[#7958d8] p-2 text-sm font-bold text-white">{saving ? "Menyimpan..." : "Simpan jadwal"}</button></form>
      <section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="flex items-center gap-2"><UserRoundCheck size={18}/><h2 className="font-bold">Jadwal terdekat</h2></div>{data.schedules.length ? <div className="mt-4 space-y-3">{data.schedules.map((item)=><div key={item.id} className="flex flex-wrap justify-between gap-3 border-b border-[#dedee8] pb-3"><div><p className="font-bold">{item.staff_name} <span className="font-normal text-[#66667a]">· {item.role_label || "Shift"}</span></p><p className="mt-1 text-xs text-[#66667a]">{new Date(item.starts_at).toLocaleString("id-ID")} sampai {new Date(item.ends_at).toLocaleString("id-ID")}</p></div>{item.pos_shift_allowed && <span className="h-fit rounded bg-[#d9ff57] px-2 py-1 font-mono text-[10px] font-bold">POS diizinkan</span>}</div>)}</div> : <p className="mt-4 text-sm text-[#66667a]">Belum ada jadwal.</p>}</section></div>
    <div className="grid gap-6 md:grid-cols-2"><section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="flex items-center gap-2"><ShieldCheck size={18}/><h2 className="font-bold">Absensi terbaru</h2></div><div className="mt-3 space-y-2">{data.attendance.map((item)=><div key={item.id} className="border-b border-[#dedee8] pb-2 text-sm"><b>{item.staff_name}</b><span className="text-[#66667a]"> · masuk {item.check_in_at ? new Date(item.check_in_at).toLocaleString("id-ID") : "-"}</span><p className="mt-1 font-mono text-[10px]">{item.method} · {item.status} · {item.check_out_at ? "sudah pulang" : "masih aktif"}</p></div>)}</div></section><section className="rounded-2xl border-2 border-[#232331] bg-white p-5 shadow-ink-md"><div className="flex items-center gap-2"><MapPin size={18}/><h2 className="font-bold">Titik absensi</h2></div>{data.sites.length ? data.sites.map((site)=><div className="mt-3 border-l-4 border-[#7958d8] bg-[#f7f6fc] p-3 text-sm" key={site.id}><b>{site.name}</b><p className="mt-1 text-xs text-[#66667a]">Token QR tersedia untuk dipasang di lokasi kerja.</p></div>) : <p className="mt-3 text-sm text-[#66667a]">Belum ada titik lokasi/QR. Tambahkan dari pengaturan HR berikutnya.</p>}</section></div>
  </div></main>;
}
